# themes settings
theme: jekyll-theme-minimal

title: "Home"
description: "2022年10月19日設立。株式会社おもしろテクノロジーのコーポレートサイト。"
logo: image/logo.png

google_analytics: G-NPHB6L4K4J

twitter:
  username: norotororo